In [1]:
import numpy as np

In [3]:
0xffffffff

4294967295

In [5]:
-100 & 0xffffffff

4294967196

In [20]:
bin(int('0xffffffff', 16))

'0b11111111111111111111111111111111'

In [3]:
a = np.random.randn(5,1)
a

array([[0.20898628],
       [0.71516205],
       [0.30486657],
       [1.57408993],
       [0.63945849]])

In [4]:
b = np.random.randn(5,1)
b

array([[-0.05499025],
       [-1.01703306],
       [-0.65587795],
       [ 0.50299549],
       [-0.44559303]])

In [5]:
np.multiply(a,b)

array([[-0.01149221],
       [-0.72734345],
       [-0.19995527],
       [ 0.79176014],
       [-0.28493824]])

In [7]:
np.dot(a,b.T)

array([[-0.01149221, -0.21254596, -0.1370695 ,  0.10511916, -0.09312283],
       [-0.03932694, -0.72734345, -0.46905902,  0.35972329, -0.31867122],
       [-0.01676469, -0.31005939, -0.19995527,  0.15334651, -0.13584642],
       [-0.0865596 , -1.60090151, -1.03241088,  0.79176014, -0.7014035 ],
       [-0.03516398, -0.65035043, -0.41940672,  0.32164474, -0.28493824]])

In [3]:
for i in reversed(range(3)):
    print(i)

2
1
0


In [23]:
bin(7)

'0b111'

In [37]:
~ 0b0111

-8

In [36]:
bin(-3)

'-0b11'

In [12]:
-10 & 0xffffffff

4294967286

In [13]:
2**32 - 10

4294967286