In [1]:
import numpy as np

In [3]:
0xffffffff

4294967295

In [5]:
-100 & 0xffffffff

4294967196

In [20]:
bin(int('0xffffffff', 16))

'0b11111111111111111111111111111111'

In [3]:
a = np.random.randn(5,1)
a

array([[0.20898628],
       [0.71516205],
       [0.30486657],
       [1.57408993],
       [0.63945849]])

In [4]:
b = np.random.randn(5,1)
b

array([[-0.05499025],
       [-1.01703306],
       [-0.65587795],
       [ 0.50299549],
       [-0.44559303]])

In [5]:
np.multiply(a,b)

array([[-0.01149221],
       [-0.72734345],
       [-0.19995527],
       [ 0.79176014],
       [-0.28493824]])

In [7]:
np.dot(a,b.T)

array([[-0.01149221, -0.21254596, -0.1370695 ,  0.10511916, -0.09312283],
       [-0.03932694, -0.72734345, -0.46905902,  0.35972329, -0.31867122],
       [-0.01676469, -0.31005939, -0.19995527,  0.15334651, -0.13584642],
       [-0.0865596 , -1.60090151, -1.03241088,  0.79176014, -0.7014035 ],
       [-0.03516398, -0.65035043, -0.41940672,  0.32164474, -0.28493824]])

In [3]:
for i in reversed(range(3)):
    print(i)

2
1
0


In [23]:
bin(7)

'0b111'

In [37]:
~ 0b0111

-8

In [36]:
bin(-3)

'-0b11'

In [12]:
-10 & 0xffffffff

4294967286

In [13]:
2**32 - 10

4294967286

In [7]:
rng = np.random.default_rng(1)
rng.random(4)

array([0.51182162, 0.9504637 , 0.14415961, 0.94864945])

In [12]:
for i in reversed(range(1,3)):
    print(i)

2
1


In [4]:
rng = np.random.default_rng(1)
rng.random((4,2))

array([[0.51182162, 0.9504637 ],
       [0.14415961, 0.94864945],
       [0.31183145, 0.42332645],
       [0.82770259, 0.40919914]])

In [4]:
a = np.random.rand(20,1)
b = np.random.rand(5,1)

np.concatenate((a,b), axis = 0)

array([[0.3326954 ],
       [0.24527308],
       [0.07777528],
       [0.83034657],
       [0.3667686 ],
       [0.83327123],
       [0.2508559 ],
       [0.5493329 ],
       [0.17977562],
       [0.93894078],
       [0.1683461 ],
       [0.35198466],
       [0.51605136],
       [0.02269594],
       [0.11126395],
       [0.17026053],
       [0.69042523],
       [0.0519426 ],
       [0.60348101],
       [0.72169535],
       [0.22982253],
       [0.81935208],
       [0.52769454],
       [0.12209469],
       [0.70557568]])